require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - app/channels/**/*
    - node_modules/**/*
    - bin/*
    - spec/**/*
    - lib/*
    - lib/tasks/*
    - db/migrate/*
    - db/schema.rb
    - public/*
    - tmp/*
    - vendor/**/*
    - config/spring.rb
    
Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
  
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 120

Rails/FilePath:
  Enabled: false

Metrics/AbcSize:
  Max: 20